ph-ee-engine:  
  zeebe:
    broker:
      contactpoint: "zeebe-zeebe-gateway:26500"
  zeebe-cluster-helm:
    global:
      elasticsearch:
        host: "ph-ee-elasticsearch"
    image:
      repository: camunda/zeebe
      tag: 1.1.0

    clusterSize: "1"
    partitionCount: "1"
    replicationFactor: "1"
    
    elasticsearch:
      enabled: false
    kibana:
      enabled: false

    extraInitContainers: |
      - name: init-ph-ee-kafka-exporter
        image: busybox:1.28
        command: ['/bin/sh', '-c']
        args: ['wget -O /exporters/ph-ee-kafka-exporter.jar "https://paymenthub-ee-dev.s3.us-east-2.amazonaws.com/jars/exporter-1.0.0-SNAPSHOT.jar"; ls -al /exporters/']
        volumeMounts:
        - name: exporters
          mountPath: /exporters/

  zeebe-operate-helm:
    enabled: true
    image:
      repository: camunda/operate
      tag: 1.1.0
    global:
      elasticsearch:
        host: "ph-ee-elasticsearch"
        clusterName: "ph-ee-elasticsearch"

  elasticsearch:
    enabled: true
    replicas: 1
    imageTag: 7.13.2
    minimumMasterNodes: 1

    #Single Node Solution
    clusterHealthCheckParams: "wait_for_status=yellow&timeout=100s" 
    master:
      readinessProbe:
        httpGet:
          path: /_cluster/health?wait_for_status=yellow&timeout=5s
          port: 9200
        initialDelaySeconds: 30
    data:
      readinessProbe:
        httpGet:
          path: /_cluster/health?wait_for_status=yellow&timeout=5s
          port: 9200
        initialDelaySeconds: 30

  

    # Shrink default JVM heap.
    esJavaOpts: "-Xmx512m -Xms512m"

    # Allocate smaller chunks of memory per pod.
    resources:
      requests:
        cpu: "200m"
        memory: "1024M"
      limits:
        cpu: "1000m"
        memory: "1024M"
    volumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 10Gi

  kibana:
    enabled: true
    imageTag: 7.13.2
    ingress:
      enabled: false
      className: "nginx"
      pathtype: ImplementationSpecific
      annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
      hosts:
        - host: analytics.ibank.financial
          paths:
            - path: /
      #tls: []
      #  - secretName: chart-example-tls
      #    hosts:
      #      - chart-example.local

    kibanaConfig:
      kibana.yml: |
        monitoring.enabled: false

  operations:
    enabled: true

  operationsMysql:
    mysqlRootPassword: "ethieTieCh8ahv"
    mysqlUser: "mifos"
    mysqlPassword: "password"
    mysqlDatabase: "tenants"
    initializationFiles:
      setup.sql: |-
        CREATE DATABASE messagegateway;
        CREATE DATABASE `ibank-india`;
        CREATE DATABASE `ibank-usa`; 
        GRANT ALL PRIVILEGES ON `ibank-india`.* TO 'mifos';
        GRANT ALL PRIVILEGES ON `ibank-usa`.* TO 'mifos';
        GRANT ALL ON *.* TO 'root'@'%';
        GRANT ALL PRIVILEGES ON messagegateway.* TO 'mifos';

  mifos_connector:
    SPRING_PROFILES_ACTIVE: "fin12,bb"
    image: "us.icr.io/phee-ns/phee-connector-ams"

  mojaloop:
    SPRING_PROFILES_ACTIVE: "bb"

  channel:
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "channel.ibank.financial"
    AWS_ACCESS_KEY: "xxx"
    AWS_SECRET_KEY: "xxx"
    image: "us.icr.io/phee-ns/phee-connector-channel"

  operations_app:
    TENANTS: "ibank-usa,ibank-india"
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "ops-bk.ibank.financial"
    image: "us.icr.io/phee-ns/ph-ee-ops-bk"

  operations_web:
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "ops-bk.ibank.financial"
    webhost: "ops.ibank.financial"
    image: "us.icr.io/phee-ns/ops-web"

  identity:
    hostname: "ops-bk.ibank.financial"

  gsma:
    SPRING_PROFILES_ACTIVE: "bb"
    image: "us.icr.io/phee-ns/ph-ee-gsma"

  mpesa:
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "mpesa.ibank.financial"
    image: "us.icr.io/phee-ns/ph-ee-mpesa"

  roster_connector:
    SPRING_PROFILES_ACTIVE: "bb"
    image: "us.icr.io/phee-ns/phee-connector-ams-pesa"

  notifications:
    SPRING_PROFILES_ACTIVE: "bb"
    image: "us.icr.io/phee-ns/ph-ee-notifications"

  bulk_processor:
    image: "us.icr.io/phee-ns/phee-bulk-processor"

  zeebe_ops:
    image: "us.icr.io/phee-ns/phee-zeebe-ops"

  messagegateway:
    image: "us.icr.io/phee-ns/message-gateway"

  importer_es:
    image: "us.icr.io/phee-ns/phee-es-importer"

  importer_rdbms:
    image: "us.icr.io/phee-ns/importer-rdbms"
