ph-ee-engine:
  zeebe:
    broker:
      contactpoint: "zeebe-zeebe-gateway:26500"
  zeebe-cluster-helm:
    global:
      elasticsearch:
        host: "ph-ee-elasticsearch"
    image:
      repository: camunda/zeebe
      tag: 1.1.0

    clusterSize: "1"
    partitionCount: "1"
    replicationFactor: "1"

    elasticsearch:
      enabled: false
    kibana:
      enabled: false

    extraInitContainers: |
      - name: init-ph-ee-kafka-exporter
        image: busybox:1.28
        command: ['/bin/sh', '-c']
        args: ['wget -O /exporters/ph-ee-kafka-exporter.jar "https://paymenthub-ee-dev.s3.us-east-2.amazonaws.com/jars/exporter-1.0.0-SNAPSHOT.jar"; ls -al /exporters/']
        volumeMounts:
        - name: exporters
          mountPath: /exporters/

  zeebe-operate-helm:
    enabled: false
    image:
      repository: camunda/operate
      tag: 1.1.0
    global:
      elasticsearch:
        host: "ph-ee-elasticsearch"
        clusterName: "ph-ee-elasticsearch"
    ingress:
      enabled: true
      className: "alb"
      path: /
      host: operate.fynarfin.io
      tls:
        enabled: true

  elasticsearch:
    enabled: true
    replicas: 1
    imageTag: 7.16.3
    minimumMasterNodes: 1

    #Single Node Solution
    clusterHealthCheckParams: "wait_for_status=yellow&timeout=100s"
    master:
      readinessProbe:
        httpGet:
          path: /_cluster/health?wait_for_status=yellow&timeout=5s
          port: 9200
        initialDelaySeconds: 30
    data:
      readinessProbe:
        httpGet:
          path: /_cluster/health?wait_for_status=yellow&timeout=5s
          port: 9200
        initialDelaySeconds: 30



    # Shrink default JVM heap.
    esJavaOpts: "-Xmx512m -Xms512m"

    # Allocate smaller chunks of memory per pod.
    resources:
      requests:
        cpu: "100m"
        memory: "1024M"
      limits:
        cpu: "1000m"
        memory: "1024M"
    volumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 10Gi

  kibana:
    enabled: false
    imageTag: 7.16.3
    ingress:
      enabled: true
      className: "alb"
      pathtype: ImplementationSpecific
      annotations:
        kubernetes.io/ingress.class: alb
        kubernetes.io/tls-acme: "true" 
      hosts:
        - host: analytics.fynarfin.io
          paths:
            - path: /
      #tls: []
      #  - secretName: chart-example-tls
      #    hosts:
      #      - chart-example.local

    kibanaConfig:
      kibana.yml: |
        monitoring.enabled: false
        xpack.encryptedSavedObjects.encryptionKey: 5f4dcc3b5aa765d61d8327deb882cf99

  operations:
    enabled: true

  operationsmysql:
    auth:
      database: "tenants"
      username: "mifos"
      password: "password"
      rootPassword: "ethieTieCh8ahv"
    initdbScripts:
      setup.sql: |-
        CREATE DATABASE messagegateway;
        CREATE DATABASE `ibank-india`;
        CREATE DATABASE `ibank-usa`; 
        GRANT ALL PRIVILEGES ON `ibank-india`.* TO 'mifos';
        GRANT ALL PRIVILEGES ON `ibank-usa`.* TO 'mifos';
        GRANT ALL ON *.* TO 'root'@'%';
        GRANT ALL PRIVILEGES ON messagegateway.* TO 'mifos';

  ph_ee_connector_ams_mifos:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/ams"
    imageTag: latest
    SPRING_PROFILES_ACTIVE: "fin12,bb"
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "100m"
      memory: "256M"
    deployment:
      annotations:
        deployTime: "{{ .Values.deployTime }}"

  ph_ee_connector_mojaloop:
    enabled: true
    image: "shanidkh/ph-ee:ph-ee-connector-mojaloop-java"
    SPRING_PROFILES_ACTIVE: "bb"
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "100m"
      memory: "256M"
    deployment:
      annotations:
        deployTime: "{{ .Values.deployTime }}"

  kafka:
    enabled: true
    image: "spotify/kafka"
    advertised:
      host: "kafka"
      port: "9092"
    limits:
      cpu: "500m"
      memory: "1G"
    requests:
      cpu: "100m"
      memory: "512M"
    deployment:
      annotations:
        deployTime: "{{ .Values.deployTime }}"

  channel:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-channel"
    imageTag: latest
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "channel.fynarfin.io"
    DFSPIDS: "ibank-usa,ibank-india"
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "100m"
      memory: "256M"
    ingress:
      enabled: true
      path: "/"
      backend:
        service:
          name: ph-ee-connector-channel
          port:
            number: 80
    deployment:
      annotations:
        deployTime: "{{ .Values.deployTime }}"


  operations_app:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/ph-ee-ops-bk"
    imageTag: latest
    SPRING_PROFILES_ACTIVE: "bb"
    tenants: "ibank-usa,ibank-india"
    hostname: "ops-bk.fynarfin.io"
    datasource:
      username: "mifos"
      password: "password"
      host: "operationsmysql"
      port: 3306
      schema: "tenants"
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "100m"
      memory: "256M"
    ingress:
      enabled: true
      path: "/"
      backend:
        service:
          name: ph-ee-operations-app
          port:
            number: 80
    deployment:
      annotations:
        deployTime: "{{ .Values.deployTime }}"

  operations_web:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-ops-web"
    imageTag: latest
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "ops.fynarfin.io"
    webhost: "ops.fynarfin.io"
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "100m"
      memory: "256M"
    ingress:
      enabled: true
      path: "/"
      backend:
        service:
          name: ph-ee-operations-web
          port:
            number: 4200

  identity:
    hostname: "ops-bk.fynarfin.io"

  ph_ee_connector_gsma:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-connector-ams-paygops"
    imageTag: latest
    SPRING_PROFILES_ACTIVE: "bb"
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "100m"
      memory: "256M"
    deployment:
      annotations:
        deployTime: "{{ .Values.deployTime }}"

  ph_ee_connector_slcb:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/ph-ee-slcb"
    imageTag: latest
    SPRING_PROFILES_ACTIVE: "bb"
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "100m"
      memory: "256M"
    deployment:
      annotations:
        deployTime: "{{ .Values.deployTime }}"

  mpesa:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/ph-mpesa"
    imageTag: latest
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "mpesa.fynarfin.io"
    tenant: "ibank-india"
    zeebe_broker_contactpoint: "zeebe-zeebe-gateway:26500"
    callback_host: "https://mpesa.ibank.financial/"
    retry_count: 3
    api_timeout: 60000
    accounts:
      roster:
        name: "roster"
        business_short_code: "7385028"
        till: "1234567"
        auth_host: "https://sandbox.safaricom.co.ke/oauth/v1/generate"
        api_host: "https://sandbox.safaricom.co.ke"
        client_key: "0pLxbN83FrOl5Nd0Fh9Zi5BQlMxSL2n5"
        client_secret: "YzuGNoJxeub8ZC6d"
        pass_key: "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
      paygops:
        name: "paygops"
        business_short_code: "668158"
        till: "9347335"
        auth_host: "https://sandbox.safaricom.co.ke/oauth/v1/generate"
        api_host: "https://sandbox.safaricom.co.ke"
        client_key: "0pLxbN83FrOl5Nd0Fh9Zi5BQlMxSL2n5"
        client_secret: "YzuGNoJxeub8ZC6d"
        pass_key: "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "100m"
      memory: "256M"
    ingress:
      enabled: true
      path: "/"
      backend:
        service:
          name: ph-ee-connector-mpesa
          port:
            number: 80
    deployment:
      annotations:
        deployTime: "{{ .Values.deployTime }}"
    skip:
      enabled: false

  roster_connector:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-roster"
    imageTag: latest
    SPRING_PROFILES_ACTIVE: "bb"
    ams:
      local:
        enabled: false
    pesacore:
      auth_header: "PaymentHub"
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "100m"
      memory: "256M"
    deployment:
      annotations:
        deployTime: "{{ .Values.deployTime }}"

  paygops_connector:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-connector-ams-paygops"
    imageTag: latest
    SPRING_PROFILES_ACTIVE: "bb"
    LOGGING_LEVEL_ROOT: "INFO"
    ams:
      local:
        enabled: false
    paygops:
      authheader: "PaymentHubTest"
      base_url: "https://feature-test1.paygops.com/"
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "100m"
      memory: "256M"
    deployment:
      annotations:
        deployTime: "{{ .Values.deployTime }}"

  notifications:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/ph-ee-notifications"
    imageTag: latest
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "notifications.fynarfin.io"
    MESSAGEGATEWAYCONFIG_HOST: "message-gateway"
    NOTIFICATION_LOCAL_HOST: "ph-ee-connector-notifications"
    NOTIFICATION_SUCCESS_ENABLED: "true"
    NOTIFICATION_FAILURE_ENABLED: "true"
    zeebe_broker_contactpoint: "zeebe-zeebe-gateway:26500"
    hostconfig:
      host: "message-gateway"
      port: 80
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "100m"
      memory: "256M"
    ingress:
      enabled: true
      path: "/"
      backend:
        service:
          name: ph-ee-connector-notifications
          port:
            number: 80
    deployment:
      annotations:
        deployTime: "{{ .Values.deployTime }}"

  connector_bulk:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-bulk-processor"
    imageTag: latest
    SPRING_PROFILES_ACTIVE: "<issue: wasnot present earlier but it is in deployment>"
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "100m"
      memory: "256M"
    deployment:
      annotations:
        deployTime: "{{ .Values.deployTime }}"

  zeebe_ops:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-zeebe-ops"
    imageTag: latest
    hostname: "zeebeops.fynarfin.io"
    zeebe_broker_contactpoint: "zeebe-zeebe-gateway:26500"
    elasticsearch_contactpoint: "ph-ee-elasticsearch:9200"
    tenants: "ibank-usa,ibank-india"
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "100m"
      memory: "256M"
    ingress:
      enabled: true
      path: "/"
      backend:
        service:
          name: ph-ee-zeebe-ops
          port:
            number: 80
    deployment:
      annotations:
        deployTime: "{{ .Values.deployTime }}"

  messagegateway:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-message-gateway"
    imageTag: latest
    secret:
      value:
        api_key: "eKiC1_JWdKy7eaTGQFHxXXjXjacr60W9Zntl"
        project_id: "PJ5ff552ce01d2978c"
    hostname: "messagegateway.fynarfin.io"
    CALLBACKCONFIG_HOST: "ph-ee-connector-notifications"
    HOSTCONFIG_HOST: "message-gateway"
    MYSQL_USERNAME: "mifos"
    MYSQL_PASSWORD: "password"
    DATASOURCE_URL: jdbc:mysql:thin://operationsmysql:3306/messagegateway
    PROVIDERSOURCE_FROMDATABASE: "disabled"
    PROVIDERSOURCE_FROMYML: "enabled"
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "100m"
      memory: "256M"
    ingress:
      enabled: true
      path: "/"
      backend:
        service:
          name: message-gateway
          port:
            number: 80

  importer_es:
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/ph-es-importer"
    imageTag: latest
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "100m"
      memory: "256M"

  importer_rdbms:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-importer-rdbms"
    imageTag: latest
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "100m"
      memory: "256M"
    datasource:
      username: "mifos"
      password: "password"
      host: "operationsmysql"
      port: 3306
      schema: "tenants"

  wildcardhostname: "*.fynarfin.io"

  tls: "" 
