apiVersion: v2
name: operations
description: A Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: 1.0.0

dependencies:
- name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 25.22.0
  condition: "prometheus.enabled"

- name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 8.0.2
  condition: "grafana.enabled"

