ph-ee-engine-oaf:  
  zeebe:
    broker:
      contactpoint: "zeebe-zeebe-gateway:26500"
  zeebe-cluster-helm:
    global:
      elasticsearch:
        host: "ph-ee-elasticsearch"
    image:
      repository: camunda/zeebe
      tag: 1.1.0

    clusterSize: "1"
    partitionCount: "1"
    replicationFactor: "1"
    
    elasticsearch:
      enabled: false
    kibana:
      enabled: false

    extraInitContainers: |
      - name: init-ph-ee-kafka-exporter
        image: busybox:1.28
        command: ['/bin/sh', '-c']
        args: ['wget -O /exporters/ph-ee-kafka-exporter.jar "https://paymenthub-ee-dev.s3.us-east-2.amazonaws.com/jars/exporter-1.0.0-SNAPSHOT.jar"; ls -al /exporters/']
        volumeMounts:
        - name: exporters
          mountPath: /exporters/

  zeebe-operate-helm:
    enabled: true
    image:
      repository: camunda/operate
      tag: 1.1.0
    global:
      elasticsearch:
        host: "ph-ee-elasticsearch"
        clusterName: "ph-ee-elasticsearch"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "kong"
        konghq.com/strip-path: "true"   
      path: /
      host: paymenthub.qa.oneacrefund.org
      tls:
        enabled: true
        secretName: oafqa-tls

  elasticsearch:
    enabled: true
    replicas: 1
    imageTag: 7.13.2
    minimumMasterNodes: 1

    #Single Node Solution
    clusterHealthCheckParams: "wait_for_status=yellow&timeout=100s" 
    master:
      readinessProbe:
        httpGet:
          path: /_cluster/health?wait_for_status=yellow&timeout=5s
          port: 9200
        initialDelaySeconds: 30
    data:
      readinessProbe:
        httpGet:
          path: /_cluster/health?wait_for_status=yellow&timeout=5s
          port: 9200
        initialDelaySeconds: 30

  

    # Shrink default JVM heap.
    esJavaOpts: "-Xmx512m -Xms512m"

    # Allocate smaller chunks of memory per pod.
    resources:
      requests:
        cpu: "200m"
        memory: "1024M"
      limits:
        cpu: "1000m"
        memory: "1024M"
    volumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 10Gi

  kibana:
    enabled: true
    imageTag: 7.13.2

    kibanaConfig:
      kibana.yml: |
        monitoring.enabled: false

  operations:
    enabled: true

  operationsMysql:
    mysqlRootPassword: "ethieTieCh8ahv"
    mysqlUser: "mifos"
    mysqlPassword: "password"
    mysqlDatabase: "tenants"
    initializationFiles:
      setup.sql: |-
        CREATE DATABASE messagegateway;
        GRANT ALL ON *.* TO 'root'@'%';
        GRANT ALL PRIVILEGES ON messagegateway.* TO 'mifos';

  channel:
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "paymenthub.qa.oneacrefund.org"
    AWS_ACCESS_KEY: "xxx"
    AWS_SECRET_KEY: "xxx"
    image: "oaftech.azurecr.io/phee-ns/ph-ee-connector-channel"

  operations_app:
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "paymenthub.qa.oneacrefund.org"
    image: "oaftech.azurecr.io/phee-ns/ph-ee-operations-app"

  operations_web:
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "paymenthub.qa.oneacrefund.org"
    webhost: "paymenthub.qa.oneacrefund.org/opsweb"
    image: "oaftech.azurecr.io/phee-ns/ops-web"

  identity:
    hostname: "ops-bk.ibank.financial"

  mpesa:
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "paymenthub.qa.oneacrefund.org"
    image: "oaftech.azurecr.io/phee-ns/ph-ee-connector-mpesa"

  roster_connector:
    SPRING_PROFILES_ACTIVE: "bb"
    image: "oaftech.azurecr.io/phee-ns/ph-ee-connector-ams-pesa"

  notifications:
    SPRING_PROFILES_ACTIVE: "bb"
    image: "oaftech.azurecr.io/phee-ns/ph-ee-notifications"
    CALLBACKCONFIG_HOST: "paymenthub.qa.oneacrefund.org/notifications"

  zeebe_ops:
    image: "oaftech.azurecr.io/phee-ns/phee-zeebe-ops"

  messagegateway:
    image: "oaftech.azurecr.io/phee-ns/message-gateway"
    MESSAGEGATEWAYCONFIG_HOST: "paymenthub.qa.oneacrefund.org/messages"

  importer_es:
    image: "oaftech.azurecr.io/phee-ns/ph-ee-importer-es"

  importer_rdbms:
    image: "oaftech.azurecr.io/phee-ns/ph-ee-importer-rdbms"
