ph-ee-engine:
  camunda-platform:
    zeebe:
      enabled: false
    zeebe-gateway:
      replicas: 0
  minio:
    enabled: false
  elasticsearch:
    enabled: false

  kibana:
    enabled: false

  operations:
    mysql:
      enabled: false
    enabled: false

  operationsmysql:
    enabled: false

  ph_ee_connector_ams_mifos:
    enabled: false

  ph_ee_connector_mojaloop:
    enabled: false

  kafka:
    enabled: false

  channel:
    enabled: false

  mockpayment:
    enabled: false

  ph_ee_connector_gsma:
    enabled: false

  operations_app:
    enabled: false

  operations_web:
    enabled: true

  ph_ee_connector_slcb:
    enabled: false

  mpesa:
    enabled: false

  roster_connector:
    enabled: false
    #remove this after updating the env-template chart
    pesacore:
      auth_header: "PaymentHub"

  paygops_connector:
    enabled: false
    #remove this after updating the env-template chart
    paygops:
      authheader: "PaymentHub"

  notifications:
    enabled: false

  connector_bulk:
    enabled: false

  zeebe_ops:
    enabled: false

  messagegateway:
    enabled: false

  importer_es:
    enabled: false

  importer_rdbms:
    enabled: false

  kong:
    enabled: false

  keycloak:
    enabled: false

  zeebe-operate:
    enabled: false

  mock-oracle:
    enabled: false

  redis:
    enabled: false

  billPay:
    enabled: false

  crm:
    enabled: false

  vouchers:
    enabled: false

  post_installation_job:
    enabled: false

fin-engine:
  communityapp:
    lookforservice: false
    enabled: true
    ingress:
      enabled: false
      hostname: "communityapp.sandbox.mifos.io"
      wildcardhostname: "communityapp.sandbox.mifos.io"
  fineract:
    enabled: false
  mariadb:
    enabled: false
  post_tenant_installation_job:
    enabled: false

operations:
  grafana:
    enabled: true
    ingress:
      enabled: false
  prometheus:
    enabled: false
