apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-dpg-importer-rdbms
  labels:
    app: ph-ee-dpg-importer-rdbms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-dpg-importer-rdbms
  template:
    metadata:
      labels:
        app: ph-ee-dpg-importer-rdbms
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    spec:
      containers:
        - name: ph-ee-dpg-importer-rdbms
          image: "{{ .Values.image }}"
          env:
            - name: kafka.brokers
              value: {{ .Values.kafka.brokers }}
            - name: kafka.consumer-group
              value: {{ .Values.kafka.consumer_group }}
          ports:
            - containerPort: 8080
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          resources:
            limits:
              memory: "{{ .Values.limits.memory }}"
              cpu: "{{ .Values.limits.cpu }}"
            requests:
              memory: "{{ .Values.requests.memory }}"
              cpu: "{{ .Values.requests.cpu }}"
#          volumeMounts:
#            - name: importer-config
#              mountPath: "/etc/config"
#      volumes:
#        - name: importer-config
#          configMap:
#            name: importer-config