{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ph-ee-dpg-importer-rdbms
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.ingress.hostname }}"
      http:
        paths:
          - path: "{{ .Values.ingress.path }}"
            pathType: Prefix
            backend:
              service:
                name: ph-ee-dpg-importer-rdbms
                port:
                  number: 80
{{- end }}
