{{- if .Values.enabled -}}
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: ph-ee-dpg-importer-rdbms
  name: ph-ee-dpg-importer-rdbms
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: ph-ee-dpg-importer-rdbms
  sessionAffinity: None
  type: ClusterIP
{{- end }}  